yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech')
]

yatube/posts/urls.py
from django.urls import path

from . import views


app_name = 'posts'

urlpatterns = [
    path(
        'group/<slug:slug>/',
        views.group_posts,
        name='group_list'
    ),
    path(
        'profile/<str:username>/',
        views.profile,
        name='profile'
    ),
    path(
        'posts/<int:post_id>/',
        views.post_detail,
        name='post_detail'
    ),
    path(
        'create/',
        views.post_create,
        name='post_create'
    ),
    path(
        'posts/<int:post_id>/edit/',
        views.post_edit,
        name='post_edit'
    ),
    path(
        '',
        views.index,
        name='index'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin

from django.urls import include, path


urlpatterns = [
    path(
        'admin/',
        admin.site.urls
    ),
    path(
        'about/',
        include(
            'about.urls',
            namespace='about'
        )
    ),
    path(
        'auth/',
        include(
            'users.urls',
            namespace='users'
        )
    ),
    path(
        'auth/',
        include('django.contrib.auth.urls')
    ),
    path(
        '',
        include(
            'posts.urls',
            namespace='posts'
        )
    ),
]

yatube/templates/includes/footer.html
<p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>

yatube/templates/includes/header.html
{% load static %}
{% block header %}
<nav class="navbar navbar-light" style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="{% url 'posts:index' %}">
      <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
      <span style="color:red">Ya</span>tube</a>
    </a>
    <ul class="nav nav-pills">
      <li class="nav-item"> 
        <a class="nav-link 
          {% if request.resolver_match.view_name  == 'about:author' %}
          active
          {% endif %}"
          href="{% url 'about:author' %}">
          Об авторе
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link 
        {% if request.resolver_match.view_name  == 'about:tech' %}
        active
        {% endif %}"
        href="{% url 'about:tech' %}">  
        Технологии
        </a>
      </li>
      {% if user.username %}
      <li class="nav-item"> 
        <a class="nav-link
          {% if request.resolver_match.view_name  == 'posts:post_create' %}
          active
          {% endif %}"
          href="{% url 'posts:post_create' %}"> 
          Новая запись</a>
      </li>
      <li class="nav-item"> 
        <a class="nav-link link-light
          {% if request.resolver_match.view_name  == 'users:password_change' %}
          active
          {% endif %}"
          href="{% url 'users:password_change' %}">
          Изменить пароль</a>
      </li>
      <li class="nav-item"> 
        <a class="nav-link link-light
          {% if request.resolver_match.view_name  == 'users:logout' %}
          active
          {% endif %}"
          href="{% url 'users:logout' %}">
          Выйти</a>
      </li>
      <li> 
        Пользователь: {{ user.username }}
      <li>
      {% else %}
      <li class="nav-item"> 
        <a class="nav-link link-light
          {% if request.resolver_match.view_name  == 'users:login' %}
          active
          {% endif %}"
          href="{% url 'users:login' %}">
          Войти</a>
      </li>
      <li class="nav-item"> 
        <a class="nav-link link-light
          {% if request.resolver_match.view_name  == 'users:signup' %}
          active
          {% endif %}"
          href="{% url 'users:signup' %}">
          Регистрация</a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>
{% endblock header %}

yatube/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
  <nav aria-label="Page navigation" class="my-5">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" 
          href="?page=1">Первая</a></li>
        <li class="page-item">
          <a class="page-link"
            href="?page={{ page_obj.previous_page_number }}">
            Предыдущая
          </a>
        </li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
          {% if page_obj.number == i %}
            <li class="page-item active">
              <span class="page-link">{{ i }}</span>
            </li>
          {% else %}
            <li class="page-item">
              <a class="page-link" href="?page={{ i }}">{{ i }}</a>
            </li>
          {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" 
            href="?page={{ page_obj.next_page_number }}">
            Следующая
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" 
            href="?page={{ page_obj.paginator.num_pages }}">
            Последняя
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}