yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech')
]

yatube/posts/urls.py
from django.urls import path

from . import views


app_name = 'posts'

urlpatterns = [
    path(
        'group/<slug:slug>/',
        views.group_posts,
        name='group_list'
    ),
    path(
        'profile/<str:username>/',
        views.profile,
        name='profile'
    ),
    path(
        'posts/<int:post_id>/',
        views.post_detail,
        name='post_detail'
    ),
    path(
        'create/',
        views.post_create,
        name='post_create'
    ),
    path(
        'posts/<int:post_id>/edit/',
        views.post_edit,
        name='post_edit'
    ),
    path(
        '',
        views.index,
        name='index'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin

from django.urls import include, path


urlpatterns = [
    path(
        'admin/',
        admin.site.urls
    ),
    path(
        'about/',
        include(
            'about.urls',
            namespace='about'
        )
    ),
    path(
        'auth/',
        include(
            'users.urls',
            namespace='users'
        )
    ),
    path(
        'auth/',
        include('django.contrib.auth.urls')
    ),
    path(
        '',
        include(
            'posts.urls',
            namespace='posts'
        )
    ),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    """Таблица, содержащая группы пользователей."""
    title = models.CharField('Сообщество', max_length=200)
    slug = models.SlugField(
        unique=True,
        default='title'
    )
    description = models.TextField('Записи сообщества')

    class Meta:
        verbose_name_plural = 'Сообщества'

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    """Таблица, содержащая сообщения (посты) пользователей."""
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        verbose_name='Дата публикации',
        auto_now_add=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name='Группа',
        help_text='Выберите группу'
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name_plural = 'Публикации'

    def __str__(self) -> str:
        return self.text[:15]

yatube/posts/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group')
        help_texts = {
            'text': 'Здесь Вы можете напечатать все, что Вы думаете об этом',
            'group': 'Выберете название сообщества для публикации',
        }

yatube/posts/views.py
import datetime

from django.conf import settings
from django.shortcuts import get_object_or_404, redirect, render
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required

from .models import Group, Post, User
from .forms import PostForm


def index(request):
    """Главная страница."""
    template1 = 'posts/index.html'
    post_list = Post.objects.all()
    paginator = Paginator(post_list, settings.NUM_OF_POSTS_ON_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'post_list': post_list,
        'title_index': 'Последние обновления на сайте'
    }
    return render(request, template1, context)


def group_posts(request, slug):
    """Cтраница  публикаций."""
    template2 = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    post_list = Post.objects.filter(group=group).all()
    paginator = Paginator(post_list, settings.NUM_OF_POSTS_ON_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'group': group,
        'title_groups': 'Записи сообщества: '
    }
    return render(request, template2, context)


def profile(request, username):
    """Cтраница  публикаций отдельного участника."""
    template3 = 'posts/profile.html'
    try:
        auser = User.objects.get(username=username)
        # post_count = Post.objects.filter(author=auser).count()
        post_list = Post.objects.filter(author=auser).all()
        paginator = Paginator(post_list, settings.NUM_OF_POSTS_ON_PAGE)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context = {
            'auser': auser,
            'page_obj': page_obj,
            # 'post_count': post_count,
            'title_author': 'Все посты пользователя ',
            'counted_posts': 'Всего постов: '
        }
        return render(request, template3, context)
    except TypeError:
        assert("Error in user profile page test_paginator")
    except AttributeError:
        assert("Error in user profile page utils")


def post_detail(request, post_id):
    """Cтраница отдельной публикации участника."""
    template4 = 'posts/post_detail.html'
    post = get_object_or_404(Post, id=post_id)
    author = post.author
    post_count = Post.objects.filter(author=author).count()
    context = {
        'author': author,
        'post_count': post_count,
        'post': post,
        'title_post': 'Пост '
    }
    return render(request, template4, context)


@login_required
def post_create(request):
    """Страница создания записи."""
    template5 = 'posts/create_post.html'
    form = PostForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            form = form.save(False)
            form.author = request.user
            form.pub_date = datetime.datetime.now()
            form.save()
            return redirect('posts:profile', username=form.author)
        else:
            context = {'form': form}
            return render(request, template5, context)
    else:
        context = {
            'form': form,
            'new_post': 'Новый пост'
        }
        return render(request, template5, context)


@login_required
def post_edit(request, post_id):
    """Страница редактирования записи."""
    template5 = 'posts/create_post.html'
    template6 = 'posts:post_detail'
    post = get_object_or_404(Post, pk=post_id)
    if post.author == request.user:
        is_edit = True
        if request.method == 'POST':
            form = PostForm(request.POST, instance=post)
            if form.is_valid():
                post1 = form.save(commit=False)
                post1.author = request.user
                post1.save()
                return redirect(template6, post_id)
            else:
                return render(
                    request,
                    template5,
                    {
                        'post_id': post_id,
                        'form': form,
                        'is_edit': is_edit
                    }
                )
        form = PostForm(instance=post)
        return render(
            request,
            template5,
            {
                'post_id': post_id,
                'form': form,
                'is_edit': is_edit
            }
        )
    else:
        return redirect(template6, post_id)

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block content %}
    <div class="container py-5" aling="center">    
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">      
                {% if is_edit %}
                Редактировать запись
                {% else %}
                Добавить запись
                {% endif %}            
              </div> 
              {% if not is_edit %} 
        <form action="/create/" method="POST">
            {% csrf_token %}<br>
            {{ form.text.label }}<br>
            {{ form.text|linebreaks }}
            <br><br>
            {{ form.group.label }}<br>
            {{ form.group|linebreaks }}
            <br><br>
            <button type="submit" class="btn btn-primary">
                  Сохранить
            </button>
        </form>
        {% else %}
        <form action="{% url 'posts:post_edit' post_id %}" method="POST">
          {% csrf_token %}<br>
          {{ form.text.label }}<br>
          {{ form.text|linebreaks }}
          <br><br>
          {{ form.group.label }}<br>
          {{ form.group|linebreaks }}
          <br><br>
          <button type="submit" class="btn btn-primary">
                Добавить
          </button>
      </form>
      {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock content %}

yatube/templates/posts/group_list.html
{% extends "base.html" %}
{% block title %}
  <title>{{ title_groups }}</title>
{% endblock title %}
{% block content %}
  <h1>{{ group.title }}</h1>
  <p>{{ group.description|linebreaks }}</p>
   {% for post1 in page_obj %}
    <ul>
      <li>
        Автор: {{ post1.author.get_full_name }}
        <a href="{% url 'posts:profile' post1.author %}">все посты пользователя</a>
      </li>
      <li>
        Дата публикации: {{ post1.pub_date|date:"d E Y" }}
      </li>
    </ul>
    <p>{{ post1.text|linebreaks }}</p> 
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include '../includes/paginator.html' %}
{% endblock content %}

yatube/templates/posts/head_block.html
{% load static %}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="icon" href= "{% static 'img/fav/fav.ico' %}" type="image">
<link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
<link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
<link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

yatube/templates/posts/index.html
{% extends "base.html" %}
{% block title %}
  <title>{{ title_index }}</title>
{% endblock title %}
{% block content %}
  <h1>{{ title_index }}</h1>
  {% for post1 in page_obj %}
    <ul>
      <li>
        Автор: {{ post1.author.get_full_name }}
      </li>
      <li>
        Дата публикации: {{ post1.pub_date|date:"d E Y" }}
      </li>
    </ul>
    <p>{{ post1.text|safe }}</p>
    {% if post1.group %}
      <a href="{% url 'posts:group_list' post1.group.slug %}">все записи группы</a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include '../includes/paginator.html' %}
{% endblock content %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% block title %}
<title>{{ title_post }} {{ post.text|truncatechars:30 }}</title>
{% endblock title %}
{% block content %}
<div class="container py-5">
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date }}
        </li>
        {% if post.group %}  
        <li class="list-group-item">
          <p>
            Группа: {{ post.group }}
        </p>
          <a href= "{% url 'posts:group_list' post.group.slug %}" >
            Все записи группы
          </a>
        {% endif %}
        </li>
        <li class="list-group-item">
            Автор: {{ author.get_full_name  }}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span > {{ post_count }} </span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' author %}">
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      <p>
        {{ post }}
      </p>
      <a class="btn btn-primary" href="../{{ post.id }}/edit">
        редактировать запись
      </a>   
    </article>
  </div>   
</div>
{% endblock content %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% block title %}
  <title>{{ title_author }}</title>
{% endblock title %}
{% block content %}
<div class="container py-5">
  <h1>{{ title_author }}{{ auser }}</h1>
  <h3>{{ counted_posts}}{{ auser.posts.count }}</h3>
      <ul>
        <li>
          Автор: {{ auser }}
          <a href="{% url 'posts:profile' auser %}">
            все посты пользователя
          </a>
        </li>
      </ul>
  {% for post1 in page_obj %}
      <ul>
        <li>
          Дата публикации: {{ post1.pub_date|date:"d E Y" }}
        </li>
      </ul>
      <p>{{ post1.text|safe }}</p>  
      <a href="{% url 'posts:post_detail' post1.id %}">
        подробная информация 
        <br> 
      </a>
      {% if post1.group %}   
        <a href="{% url 'posts:group_list' post1.group.slug %}">
          все записи группы 
        </a> 
      {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
{% include '../includes/paginator.html' %}
</div>
{% endblock content %}

yatube/templates/posts/update_post.html
{% extends "base.html" %}
{% block title %}
<title>Редактирование поста</title>
{% endblock %}
{% block content %}
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">       
                Редактировать пост             
              </div>
              <div class="card-body">        
                <form method="post" action="../">
                  <input type="hidden" name="csrfmiddlewaretoken" value="">            
                  <div class="form-group row my-3 p-3">
                    <label for="id_text">
                      Текст поста                  
                      <span class="required text-danger" >*</span>                  
                    </label>
                     {% csrf_token %}
                     {{ form.text }}       
                    <small id="id_text-help" class="form-text text-muted">
                      Текст редактируемого поста
                    </small>                  
                  </div>            
                  <div class="form-group row my-3 p-3">
                    <label for="id_group">
                      {{ form.group }}              
                    </label>
                    <small id="id_group-help" class="form-text text-muted">
                      Группа, к которой будет относиться пост
                    </small>
                  </div>
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      Добавить
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock content %}